# Generated by Django 5.2.7 on 2025-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicebooking_projected_cost_servicebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
