# Generated by Django 6.0 on 2025-12-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_member_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
