# Generated by Django 5.2.7 on 2025-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
