# Generated by Django 5.2.7 on 2025-12-12 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('clarinet', 'Clarinet'), ('trumpet', 'Trumpet'), ('saxophone', 'Saxophone'), ('piano', 'Piano/Guitar'), ('bass', 'Bass Guitar'), ('drums', 'Drums'), ('vocals', 'Vocals'), ('other', 'Other')], max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Brief bio or description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('live', 'Live Performance'), ('weddings', 'Weddings'), ('corporate', 'Corporate Events')], default='live', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Caption or description for this gallery item'),
        ),
    ]
